apiVersion: apps/v1
kind: Deployment
metadata:
  name: jt
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: jt
  template:
    metadata:
      labels:
        app: jt
    spec:
      containers:
        - name: main
          image: sikalabs/hello-world-server
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: TEXT
              value: "JTFG!"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
